config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'quiz#index'

  resources :quiz do
    post :update_progress, to: 'quiz#update_progress'
    post :add_guest, to: 'quiz#add_guest'
    get :get_progress, to: 'quiz#get_progress'

    resources :question do
      post 'submit_answer', to: 'question#submit_answer'
    end
  end

  resources :series

  get :join, to: 'quiz#join'

  get :health, to: 'health#index'
end

app/models/quiz.rb
# frozen_string_literal: true

class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions
  belongs_to :series, optional: true

  validates_uniqueness_of :code, case_sensitive: false

  before_save :upcase_code

  class << self
    def unique_code
      code = nil
      loop do
        code = random_code
        break if Quiz.find_by(code: code).nil?
      end
      code
    end

    def random_code
      Array.new(5).map { |_e| [*'A'..'Z'].sample }.join
    end
  end

  def results
    QuestionUser
      .joins(:user)
      .where(question: [questions])
      .group(:user_id)
      .select(
        'question_users.*, users.nickname as team, ' \
        'IFNULL(SUM(points), 0) as total_points'
      )
      .order(total_points: :desc)
  end

  def answer_formatter
    @answer_formatter ||= AnswerFormatter.new(:upcase_first)
  end

  private

  def upcase_code
    code.upcase!
  end
end

app/models/quiz/answer_formatter.rb
# frozen_string_literal: true

class Quiz
  class AnswerFormatter
    def initialize(operation)
      raise ArgumentError if operation != :upcase_first

      @operation = operation
    end

    def format(answer)
      answer&.public_send(@operation)
    end
  end
end

app/controllers/quiz_controller.rb
# frozen_string_literal: true

class QuizController < ApplicationController
  class ConflictException < RuntimeError; end

  rescue_from ConflictException, with: :conflict_handler

  def conflict_handler(_exception)
    render status: :conflict, json: progress_data
  end

  def index
    @quizzes_by_series =
      current_user.quizzes
                  .group_by(&:series)
                  .sort_by { |k, _v| k&.name.to_s }
                  .to_h
  end

  def join
    quiz = Quiz.find_by(code: params[:code].upcase)
    if quiz.nil?
      flash[:error] = 'Quiz not found'
      return redirect_to root_url
    end

    redirect_to quiz_url(quiz.id)
  end

  def show
    @quiz = Quiz.find(params[:id])
    @question = Question.find_by(id: @quiz.cursor)

    return render :waiting if @question.nil?

    redirect_to quiz_question_url(quiz_id: @quiz.id, id: @question.id)
  end

  def new
    @quiz = Quiz.new(user: current_user, code: Quiz.unique_code)
  end

  def create
    quiz = Quiz.new(params.require(:quiz).permit(:name, :code))
    quiz.user = current_user
    quiz.save!
    redirect_to edit_quiz_url id: quiz.id
  end

  def edit
    @quiz = Quiz.find(params[:id])
    authorize! :update, @quiz

    @column_headers = column_headers
    @column_data = column_data
    @progress_data = progress_data
    @questions_data = questions_data
  end

  def update
    quiz = Quiz.find(params[:id])
    authorize! :update, quiz

    quiz.update!(
      params.require(:quiz).permit(:name, :code, :cursor, :series_id)
    )
    redirect_to edit_quiz_url id: quiz.id
  end

  def update_progress
    @quiz = Quiz.find(params[:quiz_id])
    authorize! :update, @quiz

    patch = params.require(:patch).permit(
      :playerId, :field, :oldValue, :newValue
    )

    update_question(patch)

    render json: progress_data
  end

  def add_guest
    @quiz = Quiz.find(params[:quiz_id])
    authorize! :update, @quiz

    user = create_guest_user
    QuestionUser.create!(
      question: @quiz.questions.first,
      user: user
    )

    render json: progress_data
  end

  def get_progress
    @quiz = Quiz.find(params[:quiz_id])
    authorize! :update, @quiz

    render json: progress_data
  end

  private

  def create_guest_user
    User.create!(
      nickname: params[:user][:nickname],
      email: "guestuser#{Random.rand(1..1e16.to_i)}@example.com",
      password: SecureRandom.alphanumeric(16),
      guest: true
    )
  end

  def update_question(patch)
    user_id = patch[:playerId]

    question_users = QuestionUser.where(
      question_id: @quiz.questions, user_id: user_id
    )

    match = field_regex.match(patch[:field])
    question_id = match[1]
    column = match[2].downcase

    question_user = question_users.find_or_create_by!(question_id: question_id)

    update_field(question_user, patch, column)
  end

  def update_field(question_user, patch, col)
    raise ActionController::BadRequest unless %w[answer points].include?(col)

    raise ConflictException if conflict?(question_user, patch[:oldValue], col)

    question_user[col] = patch[:newValue]
    question_user.save!
  end

  def conflict?(question_user, old_val, column)
    return false if [old_val, question_user[column]].all?(&:blank?)

    old_val = BigDecimal(old_val) if column == 'points' && old_val.present?
    old_val != question_user[column]
  end

  def field_regex
    /question(\d+)(Answer|Points)/
  end

  def column_headers
    ['Rank', 'Team', 'Total Points'] + @quiz.questions.flat_map do |question|
      [question.title, 'Points']
    end + ['Total Points']
  end

  def column_data
    cols = [{ data: 'rank' }, { data: 'team' }, { data: 'totalPoints' }]

    @quiz.questions.each do |question|
      tag = "question#{question.id}"
      cols << { data: "#{tag}Answer" }
      cols << { data: "#{tag}Points" }
    end

    cols << { data: 'totalPoints' }
  end

  def questions_data
    @quiz.questions.map do |question|
      {
        id: question.id,
        title: question.title,
        expired: question.expired
      }
    end
  end
end

app/helpers/quiz_helper.rb
# frozen_string_literal: true

module QuizHelper
end

app/views/quiz/edit.html.erb
<div class="row">
  <div class="col-12 mt-2">
    <h2>Edit quiz</h2>
    <%= form_for @quiz, url: quiz_url(id: @quiz.id) do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%=
          f.label :code,
                  'ID code (a short code that people can use to find your quiz)'
        %>
        <%= f.text_field :code, class: 'form-control text-uppercase' %>
      </div>
      <div class="form-group">
        <%= f.label :series_id, 'Quiz series' %>
        <%=
          link_to '(create new series)',
                  new_series_url(redirect_to: request.url)
        %>
        <%=
          f.collection_select :series_id,
                              @quiz.user.series,
                              :id,
                              :name,
                              { include_blank: true },
                              { class: 'custom-select' }
        %>
      </div>
      <div class="form-group">
        <%= f.label :cursor, 'Current question' %>
        <%=
          f.collection_select :cursor,
                              @quiz.questions,
                              :id,
                              :title,
                              { include_blank: true },
                              { class: 'custom-select' }
        %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
<div class="row mt-4">
  <div class="col-12">
    <h3>Questions</h3>
    <p id="questions-console">Changes will be autosaved</p>
    <%=
      tag.div(
        id: 'questions-root',
        'data-quiz-json': @questions_data.to_json,
        'data-base-url': quiz_question_index_url(quiz_id: @quiz.id)
      )
    %>

    <%= form_for(:question, url: quiz_question_index_url(quiz_id: @quiz.id)) do |f| %>
      <%= f.text_field :title %>
      <%= f.submit 'Add question' %>
    <% end %>
  </div>
</div>
<div class="row mt-4">
  <div class="col-12">
    <h3>Answers</h3>
    <p id="quiz-console">Changes will be autosaved</p>
    <%=
      tag(
        :div, id: 'quiz-root',
        'data-progress-json': @progress_data.to_json,
        'data-base-url': quiz_question_index_url(quiz_id: @quiz.id),
        'data-column-headers': @column_headers.to_json,
        'data-column-data': @column_data.to_json,
        'data-update-progress-url': quiz_update_progress_url(quiz_id: @quiz.id),
        'data-get-progress-url': quiz_get_progress_url(quiz_id: @quiz.id)
      )
    %>

    <%=
      form_for(:user,
               url: quiz_add_guest_url(quiz_id: @quiz.id),
               remote: true,
               html: { id: 'add-guest-form' }) do |f|
    %>
      <%= f.text_field :nickname, placeholder: 'Nickname' %>
      <%= f.submit 'Add guest player' %>
    <% end %>
    <button id="export-csv" class="btn btn-primary">Export CSV</button>
  </div>
</div>

app/views/quiz/index.html.erb
<div class="row">
  <div class="col-12 mt-2">
    <h2>Find a quiz</h2>
    <%= form_with(url: '/join', method: 'get', local: true) do %>
      <div class="form-group">
        <%= text_field_tag :code, nil, placeholder: 'Quiz ID',
                           class: 'form-control text-uppercase' %>
      </div>
      <%= submit_tag 'Join', class: 'btn btn-primary' %>
    <% end %>
    <div class="mt-4">
      <h2>Your quizzes</h2>
      <% @quizzes_by_series.each do |series, quizzes| %>
        <h6 class="mt-4">
          <% if series %>
            <%= link_to series.name, series_url(series.id) %>
          <% else %>
            No series
          <% end %>
        </h6>
        <div class="list-group">
          <% quizzes.each do |quiz| %>
            <%= link_to quiz.name, edit_quiz_url(quiz.id),
                        class: 'list-group-item list-group-item-action' %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="mt-4">
      <%= link_to 'Create a quiz', new_quiz_url %>
    </div>
  </div>
</div>

app/views/quiz/new.html.erb
<div class="row">
  <div class="col-12 mt-2">
    <h2>Create a quiz</h2>
    <%= form_for @quiz, url: quiz_index_url do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%=
          f.label :code,
                  'ID code (a short code that people can use to find your quiz)'
        %>
        <%= f.text_field :code, class: 'form-control text-uppercase' %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/quiz/show.html.erb
<p><%= @quiz.name %></p>
<p><%= @quiz.inspect %></p>
<p><%= @quiz.questions.to_a %></p>

app/views/quiz/waiting.html.erb
<h2>Waiting for the quiz to start...</h2>
<%= render 'autorefresh' %>