config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'quiz#index'

  resources :quiz do
    post :update_progress, to: 'quiz#update_progress'
    post :add_guest, to: 'quiz#add_guest'
    get :get_progress, to: 'quiz#get_progress'

    resources :question do
      post 'submit_answer', to: 'question#submit_answer'
    end
  end

  resources :series

  get :join, to: 'quiz#join'

  get :health, to: 'health#index'
end

app/controllers/series_controller.rb
# frozen_string_literal: true

class SeriesController < ApplicationController
  def show
    @series = Series.find(params[:id])
    @leaderboard_json = @series.leaderboard.to_json
  end

  def new
    @series = Series.new
    @redirect_to = params[:redirect_to]
  end

  def create
    series = Series.new(params.require(:series).permit(:name))
    series.user = current_user
    return redirect_to(params[:redirect_to] || root_url) if series.save

    flash[:error] = series.errors.full_messages.first
    redirect_to new_series_url(redirect_to: params[:redirect_to])
  end
end

app/helpers/series_helper.rb
# frozen_string_literal: true

module SeriesHelper
end

app/views/series/new.html.erb
<div class="row">
  <div class="col-12 mt-2">
    <h2>Create a quiz series</h2>
    <%= form_for @series, url: series_index_url do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= hidden_field_tag :redirect_to, @redirect_to %>
      </div>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/series/show.html.erb
<div class="row">
  <h2><%= @series.name %></h2>
</div>
<div class="row mt-4">
  <%=
    tag.div(
      id: 'leaderboard-root',
      'data-leaderboard-json': @leaderboard_json
    )
  %>
</div>